name: dtg5
channels:
- pytorch
dependencies:
- python=3.8.5
- anaconda
- cudatoolkit=10.
- numpy
- pip
- pip:
  - gym  #
  - d4rl  #
  - mujoco-py  #
  - numpy==1.20.3
  - torch  #
  - transformers==4.5.1
  - wandb==0.16.1  #
 ##pip install -U typing_extensions
